account/urls.py
from django.urls import include
from django.urls import path

from account import views


app_name = "account"
urlpatterns = [
    # TODO: 랜딩 페이지 뷰 및 연결 url - https://www.maemaelog.com/
    # path('', views.landing_page, name='landing-page'),

    # TODO: 로그인 상태에서 개인 프로필 페이지 url - https://www.maeamelog.com/nickname/profile/
    # path('<slug:nickname>/profile/', views.user_profile, name='user-profile'),
    path("", views.index, name="home"),
    path("register/", views.register, name="register"),
    path("log-in/", views.log_in, name="log-in"),
    path("log-out/", views.log_out, name="log-out"),
    path("withdraw/", views.withdraw, name="withdraw"),
    path("password/change", views.password_change, name="password-change"),
    path("profile-edit", views.profile_edit, name="profile-edit"),
    path("account-list", views.account_list, name="account-list"),
    path("create-account", views.create_account, name="create-account"),
    path("<int:account_id>/update-account/", views.update_account, name="update-account"),
    path("<int:account_id>/delete-account/", views.delete_account, name="delete-account"),

]

maemaelog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('account.urls')),

    # 로그인 후 매매일지 대시보드로 연결 url - ex. https://www.maemaelog.com/nickname/
    path('', include('tradelog.urls')),
    path('tradestats/', include('tradestats.urls')),

    path('admin/', admin.site.urls),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html"),
       name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),
       name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/account_menu.html
<div class="h-screen w-1/3 bg-white">
    <ul id="account_menu">
        <li id="profile" class="menu-item profile p-4 text-center">
            <a href="{% url 'account:profile-edit' %}">회원정보 수정</a>
        </li>
        <li id="password-change" class="menu-item p-4 text-center">
            <a href="{% url 'account:password-change' %}">비밀번호 변경</a>
        </li>
        <li id="withdraw" class="menu-item p-4 text-center">
            <a href="{% url 'account:account-list' %}">계좌 리스트 수정</a>
        </li>
        <li id="withdraw" class="menu-item p-4 text-center">
            <a href="{% url 'account:withdraw' %}">회원탈퇴</a>
        </li>
    </ul>
</div>

templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% tailwind_css v='2' %}
    <title>{% block title %}매매일지{% endblock %}</title>
    <style>
        body{
            background-color: #E7F7F3;
        }
    </style>
</head>
<body>
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
    {% block script %}{% endblock %}
</body>
</html>

templates/nav.html
{% load static %}
<nav class="w-screen h-16 bg-white flex items-center justify-between px-16 text-primary fixed top-0 border border-line">
    <div id="logo">
        <a class="text-2xl" href="{% url 'account:home' %}">MAEMAE</a>
    </div>
    <!-- <ul id="menu">
        {% if user.is_authenticated %}
            <li id="profile" class="menu-item profile">
                <a href="{% url 'account:profile-edit' %}">{{ user.username }}</a>
            </li>
            <li id="logout" class="menu-item">
                <a href="/log-out">로그아웃</a>
            </li>
        {% else %}
            <li id="login" class="menu-item solid">
                <a href="/log-in">로그인</a>
            </li>
            <li id="register" class="menu-item">
                <a href="/sign-in">가입하기</a>
            </li>
        {% endif %}
    </ul> -->

    <div class="flex gap-2 items-center">
        {% if user.is_authenticated %}
        <a href="{% url 'account:profile-edit' %}">{{ user.username }}

        
        <a href="{% url 'account:profile-edit' %}">
            {% if profile.profile_image %}
            <img class="w-8 h-8 rounded-full" src="{{profile.profile_image.url}}" id="profile_img_thumbnail">
            {% else %}
            <img class="w-8 h-8 rounded-full" src="{% static '/image/profileimg_empty.png' %}" id="profile_img_thumbnail">
            {% endif %}
        </a>
        <a href="/log-out">로그아웃</a>
        {% else %}
        <a href="/log-in">로그인</a>
        <a href="/register">가입하기</a>

        {% endif %}
    </div>
</nav>