account/urls.py
from django.urls import include
from django.urls import path

from account import views


app_name = "account"
urlpatterns = [
    # TODO: 랜딩 페이지 뷰 및 연결 url - https://www.maemaelog.com/
    # path('', views.landing_page, name='landing-page'),

    # TODO: 로그인 상태에서 개인 프로필 페이지 url - https://www.maeamelog.com/nickname/profile/
    # path('<slug:nickname>/profile/', views.user_profile, name='user-profile'),
    path("", views.index, name="home"),
    path("register/", views.register, name="register"),
    path("log-in/", views.log_in, name="log-in"),
    path("log-out/", views.log_out, name="log-out"),
    path("withdraw/", views.withdraw, name="withdraw"),
    path("password/change", views.password_change, name="password-change"),
    path("profile-edit", views.profile_edit, name="profile-edit"),
    path("account-list", views.account_list, name="account-list"),
    path("create-account", views.create_account, name="create-account"),
    path("<int:account_id>/update-account/", views.update_account, name="update-account"),
    path("<int:account_id>/delete-account/", views.delete_account, name="delete-account"),

]

maemaelog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('account.urls')),

    # 로그인 후 매매일지 대시보드로 연결 url - ex. https://www.maemaelog.com/nickname/
    path('', include('tradelog.urls')),
    path('tradestats/', include('tradestats.urls')),

    path('admin/', admin.site.urls),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset.html"), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html"),
       name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),
       name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tradelog/urls.py
from django.urls import path
from tradelog import views
from django.conf.urls import url

app_name = 'tradelog'
urlpatterns = [
    # TODO: 매매일지 대시보드 url - https://www.maemaelog.com/nickname/
    # path('<slug:nickname>/', name='dashboard'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('dashboard/<slug:tradelog_code>',views.dashboard, name='dashboard'),
    path('create/', views.create, name='create'),
    path('detail/<int:tradelog_id>', views.detail, name="detail"),
    path('update/<int:tradelog_id>', views.update, name="update"),
    path('delete/<int:tradelog_id>', views.delete, name="delete"),
    url(
        r'^stockname-autocomplete/$',
        views.NameAutocompleteFromList.as_view(),
        name='stockname-autocomplete',
    )

    
]

tradelog/models.py
from datetime import date
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class TradeLog(models.Model):
    TRADE_TYPE = [
        ('B', '매수'),
        ('S', '매도')
    ]

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField("stock name", max_length=40)
    code = models.CharField("stock code", max_length=20)
    trade_at = models.DateTimeField("trade date", default=timezone.now())
    price = models.IntegerField("trade price")
    amount = models.IntegerField("trade volume")
    type = models.CharField("trade type", max_length=1, choices=TRADE_TYPE)
    account = models.ForeignKey('Account', on_delete=models.RESTRICT)
    description = models.TextField("trade description")
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.name

    def get_trade_type(self):
        tradeType = {
            "B": "매수",
            "S": "매도",
        }
        return tradeType[self.type]

class Account(models.Model):
    BROKERAGE_NAME = [
        ('KW', 'Kiwoom'),
        ('SS', 'Samsung'),
        ('MA', 'Mirae Asset'),
        ('KI', 'Korea Investment'),
        ('DW', 'Daewoo'),
        ('SH', 'Shinhan'),
        ('KM', 'Kookmin'),
        ('SY', 'Shinyoung'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField("account name", max_length=40)
    number = models.CharField("account number", max_length=20)
    brokerage = models.CharField("brokerage name", max_length=2, choices=BROKERAGE_NAME)
    fee = models.FloatField("transaction fee")
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

tradelog/forms.py
from django import forms
from django.forms import widgets
from .models import TradeLog
from dal import autocomplete

class CreateForm(forms.ModelForm):
    class Meta:
        model = TradeLog
        fields = '__all__'
        exclude = ['user','code']
        labels = {
            'name' : '종목명',
            'trade_at' : '매매 일자',
            'price' : '매매 단가',
            'amount' : '수량',
            'type' : '매수/매도',
            'account' : '계좌',
            'description' : '매매 이유'
        }
        widgets = {
            'description' : widgets.Textarea(attrs={
                'placeholder' : '매매이유를 입력하세요',
                'cols' : 20,
                'rows' : 10,
                }),
            'name' : autocomplete.ListSelect2(url='tradelog:stockname-autocomplete'),
            'trade_at' : forms.DateInput(format=('%Y/%m/%d')),

        }

tradelog/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404

from account.models import Profile
from .models import TradeLog
from .forms import CreateForm
import pandas as pd
import requests
from dal import autocomplete
from datetime import datetime, timedelta

res10 = requests.get('http://marketdata.monple.com/api/').json()

StockNameList = []
StockTickerList = []

for i in range(len(res10)):
    StockNameList.append(res10[i]['name'])
    StockTickerList.append(res10[i]['ticker'])

StockNameTickerDF = pd.DataFrame(zip(StockNameList, StockTickerList), columns=['name', 'code'])


def get_code_by_stock_name(name):
    code1 = StockNameTickerDF[StockNameTickerDF['name'] == name]['code'].values[0]
    return code1



def dashboard(request, tradelog_code=None):
    if not request.user.is_authenticated:
        return redirect("account:log-in")

    context = getDashBoardData(request, tradelog_code)

    return render(request, 'tradelog/dashboard.html', context)


def getDashBoardData(request, tradelog_code=None):
    if tradelog_code == None:
        posts = TradeLog.objects.filter(user=request.user).order_by('-trade_at')
    elif tradelog_code != None:
        posts = TradeLog.objects.filter(user=request.user, code=tradelog_code).order_by('-trade_at')
        # return render(request, 'tradelog/dashboard.html', {'posts': posts})

    #stockrank
    mystock_rank_object = TradeLog.objects.filter(user=request.user)
    mystock_rank_raw1 = pd.DataFrame(mystock_rank_object.values())
    mystock_rank_raw1.loc[mystock_rank_raw1['type'] == 'S', 'amount'] *= -1
    mystock_rank_raw2 = mystock_rank_raw1.groupby('name')['amount'].sum().sort_values(ascending=False)
    mystock_rank_raw3 = mystock_rank_raw2.head(10)

    tradelog_raw = pd.DataFrame((TradeLog.objects.filter(user=request.user)).values())


    # total_sell&buy
    total_sell = format(int(sum(
        tradelog_raw[tradelog_raw['type'] == 'S']['price'] * tradelog_raw[tradelog_raw['type'] == 'S']['amount'])),
                        ',d')
    total_buy = format(int(sum(
        tradelog_raw[tradelog_raw['type'] == 'B']['price'] * tradelog_raw[tradelog_raw['type'] == 'B']['amount'])),
                       ',d')

    # total_asset
    tradelog_raw_minus1 = tradelog_raw
    tradelog_raw_minus1.loc[tradelog_raw['type'] == 'S', 'amount'] *= -1
    tradelog_raw_gb_codeamount = tradelog_raw_minus1.groupby('code').sum()['amount']
    tradelog_raw_codeamount = pd.DataFrame(zip(tradelog_raw_gb_codeamount.index, tradelog_raw_gb_codeamount.values),
                                           columns=['code', 'amount'])
    # d_today_raw = datetime.today()
    # d_today = d_today_raw.strftime('%Y-%m-%d')
    # d_yesterday_raw = d_today_raw + timedelta(days=-2)
    # d_yesterday = d_yesterday_raw.strftime('%Y-%m-%d')
    # d_yyesterday_raw = d_today_raw + timedelta(days=-3)
    # d_yyesterday = d_yyesterday_raw.strftime('%Y-%m-%d')
    daylist_raw = list(requests.get('http://marketdata.monple.com/api/005930/').json()['data'].keys())
    d_yesterday= daylist_raw[len(daylist_raw) - 1]
    d_yyesterday = daylist_raw[len(daylist_raw) - 2]



    code_user = tradelog_raw_codeamount.code
    endprice_yesterday_raw = []
    for i in code_user:
        res = requests.get(f'http://marketdata.monple.com/api/{i}/')
        endprice_yesterday_raw.append(res.json()['data'][d_yesterday])
    endprice_yesterday = pd.DataFrame(zip(code_user, endprice_yesterday_raw), columns=['code', 'price_end'])

    total_asset_raw = tradelog_raw_codeamount.join(endprice_yesterday.set_index('code')['price_end'], on='code')
    total_asset_forcal = sum(total_asset_raw.amount * total_asset_raw.price_end)
    total_asset = format(int(sum(total_asset_raw.amount * total_asset_raw.price_end)), ',d')

    # principal
    tradelog_raw_buy = tradelog_raw[tradelog_raw['type'] == 'B'][['code', 'amount', 'price']]
    tradelog_raw_buy['amountprice'] = tradelog_raw_buy.amount * tradelog_raw_buy.price
    tradelog_raw_buy_gb = tradelog_raw_buy.groupby('code').sum()[['amountprice', 'amount']]
    tradelog_raw_buy_gb['avg'] = tradelog_raw_buy_gb.amountprice / tradelog_raw_buy_gb.amount
    buyavg_raw = pd.DataFrame(zip(tradelog_raw_buy_gb.index, tradelog_raw_buy_gb.avg, ), columns=['code', 'avg'])
    buyavg = buyavg_raw.join(tradelog_raw_codeamount.set_index('code')['amount'], on='code')
    buyavg['avgamount'] = buyavg.avg * buyavg.amount
    principal_raw = sum(buyavg.avgamount)
    principal = format(int(principal_raw), ',d')

    # total_return
    total_return_raw = total_asset_forcal - principal_raw
    total_return = format(int(total_return_raw), ',d')

    # today_return
    total_asset_raw2 = total_asset_raw
    total_asset_raw2.rename(columns={'price_end': 'pricey'}, inplace=True)

    code_user2 = total_asset_raw2.code
    endprice_yyesterday_raw = []
    for i in code_user2:
        res = requests.get(f'http://marketdata.monple.com/api/{i}/')
        endprice_yyesterday_raw.append(res.json()['data'][d_yyesterday])
    endprice_yyesterday = pd.DataFrame(zip(code_user, endprice_yyesterday_raw), columns=['code', 'priceyy'])

    total_return_raw = total_asset_raw2.join(endprice_yyesterday.set_index('code')['priceyy'], on='code')
    today_return = format(int(sum(
        (total_return_raw.amount * total_return_raw.pricey) - (total_return_raw.amount * total_return_raw.priceyy))),
                          ',d')

    # chart
    tradelog_raw_forchart = tradelog_raw_minus1.groupby(['trade_at', 'code']).sum()['amount']
    tradelog_raw_forchart_date = []
    tradelog_raw_forchart_code = []

    for i in tradelog_raw_forchart.index:
        tradelog_raw_forchart_date.append(i[0].strftime('%Y-%m-%d'))
        tradelog_raw_forchart_code.append(i[1])

    tradelog_raw2_forchart = pd.DataFrame(
        zip(tradelog_raw_forchart_date, tradelog_raw_forchart_code, tradelog_raw_forchart.values),
        columns=['date', 'code', 'amount'])

    price_forchart = []
    for i in range(len(tradelog_raw2_forchart)):
        res = requests.get(f'http://marketdata.monple.com/api/{tradelog_raw2_forchart.code[i]}/')
        price_forchart.append(res.json()['data'][tradelog_raw2_forchart.date[i]])

    tradelog_raw2_forchart['price'] = price_forchart
    tradelog_raw2_forchart['amountprice'] = tradelog_raw2_forchart.amount * tradelog_raw2_forchart.price
    tradelog_forchart = tradelog_raw2_forchart.groupby('date').sum()['amountprice']
    tradelog_forchart_df = pd.DataFrame(zip(tradelog_forchart.index, tradelog_forchart.values),
                                        columns=['date', 'amountprice'])

    total_asset_perday = []
    for i in range(len(tradelog_forchart_df)):
        total_asset_perday.append(sum(tradelog_forchart_df['amountprice'][0:i + 1]))
    tradelog_forchart_df['total_asset'] = total_asset_perday
    tradelog_forchart_df_sort = tradelog_forchart_df.sort_values(by='date', ascending=False)

    date_forchart = list(tradelog_forchart_df_sort.date[0:7])
    totalasset_forchart = list(tradelog_forchart_df_sort.total_asset[0:7])
    date_forchart.reverse()
    totalasset_forchart.reverse()

    context = {'mystock_rank': dict(zip(mystock_rank_raw3.index, mystock_rank_raw3.values)),
               "posts": posts,
               'total_sell': total_sell,
               'total_buy': total_buy,
               'total_asset': total_asset,
               'principal': principal,
               'total_return': total_return,
               'today_return': today_return,
               'date_forchart': date_forchart,
               'totalasset_forchart': totalasset_forchart,
               "posts": posts,
               }
    profile = Profile.objects.get(user=request.user)
    if profile:
        context["profile"] = profile

    return context


def create(request):
    form = CreateForm()
    failed_message = ""
    if (request.method == 'POST'):
        tradelog = TradeLog()
        tradelog.user = request.user
        tradelog.code = get_code_by_stock_name(request.POST["name"])
        form = CreateForm(request.POST, instance=tradelog)

        # 가격과 거래량 검사
        price = int(request.POST['price'])
        volume = int(request.POST['amount'])
        if price <= 0 or volume <= 0:
            failed_message = "가격과 거래량은 0이상이어야 합니다."
        else:
            if form.is_valid():
                form.save()
                return redirect('tradelog:dashboard')
            else:
                pass
    else:
        form = CreateForm()
    context = getDashBoardData(request)
    context['failed_message'] = failed_message
    context['isCreate'] = True
    context['form'] = form
    return render(request, 'tradelog/dashboard.html', context)


def detail(request, tradelog_id):
    tradelog_detail = get_object_or_404(TradeLog, pk=tradelog_id)
    return render(request, 'tradelog/detail.html', {'tradelog_detail': tradelog_detail, })


def update(request, tradelog_id):
    context = {}
    failed_message=""
    my_tradelog = get_object_or_404(TradeLog, pk=tradelog_id)
    if request.method == 'POST':
        update_form = CreateForm(request.POST, instance=my_tradelog)

        # 가격과 거래량 검사
        price = int(request.POST['price'])
        volume = int(request.POST['amount'])
        if price <= 0 or volume <= 0:
            failed_message = "가격과 거래량은 0이상이어야 합니다."
        else:
            if update_form.is_valid():
                update_form.save()
                return redirect('tradelog:dashboard')
            else:
                pass
    else:
        update_form = CreateForm(instance=my_tradelog)
    context = getDashBoardData(request)
    context['failed_message'] = failed_message
    context['isUpdate'] = True
    context['update_form'] = update_form
    return render(request, 'tradelog/dashboard.html', context)
    #
    # return render(request, 'tradelog/update.html', context)


def delete(request, tradelog_id):
    my_tradelog = get_object_or_404(TradeLog, pk=tradelog_id)

templates/tradelog/dashboard.html
{% extends 'base.html' %}
{% block title %}매매일지 - 대시보드{% endblock %}
{% block content %}
    {% include 'tradelog/form_create.html' %}
    {% include 'tradelog/update.html' %}
    <div id="content" class="min-h-screen flex justify-between px-16 pt-16 gap-x-2">
        <div class="w-1/3 h-auto bg-white">
            <div id="sidebar-left" class="w-full">
                {% include 'tradestats/profile.html' %}
                {% include 'tradestats/sidebar_left.html' %}
            </div>
        </div>
        <div class="w-1/2 h-auto bg-white">
            <div id="feed" class="w-full h-full">
                {% include 'tradelog/feed.html' %}
            </div>
        </div>
        <div class="w-1/4 h-auto bg-white">
            <div id="sidebar-right" class="w-full">
                {% include 'tradelog/sidebar_right.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/tradelog/detail.html
<h2>주식 종목</h2>
{{ tradelog_detail.name }}

<h2>코드</h2>
{{ tradelog_detail.code }}

<h2>시간</h2>
{{ tradelog_detail.trade_at }}




<!-- name = models.CharField("stock name", max_length=40)
code = models.CharField("stock code", max_length=20)
trade_at = models.DateTimeField("trade date", default=timezone.now())
price = models.IntegerField("trade price")
amount = models.IntegerField("trade volume")
type = models.CharField("trade type", max_length=1, choices=TRADE_TYPE)
account = models.ForeignKey('Account', on_delete=models.RESTRICT)
description = models.TextField("trade description")
create_at = models.DateTimeField(auto_now_add=True)
update_at = models.DateTimeField(auto_now=True) -->

templates/tradelog/feed.html
{% load static %}
<div class="border-b p-3 flex justify-end ">
        <a class="box-border bg-primary px-4 py-1 rounded-2xl text-white" href='{% url 'tradelog:create' %}'>매매일지 작성</a>
</div>
<!-- 이 공간에는 블로그 글들의 목록을 보여줄 예정 -->
{% for post in posts %}
        <div class="border-b p-4">
                <div class="flex justify-between items-start">
                        <div class="flex items-center gap-2">
                                <img src="{% static '/image/profileimg_empty.png' %}" class="w-8 h-8 rounded-full bg-gray-100 inline"/>
                                <div> 
                                        <a href="{% url 'tradelog:dashboard' post.code %}"><span class="font-semibold text-lg">{{ post.name }}</span>
                                                <span class="font-light text-sm">({{ post.code }})</span></a>
                                </div>
                        </div> 
                        <div class="px-8 py-2 flex items-start justify-end gap-8 text-center">
                                <div>
                                        <p class="text-sm">매수/매도</p>
                                        <p class="text-lg">{{ post.get_trade_type }}</p>
                                </div>
                                <div>
                                        <p class="text-sm">가격</p> 
                                        <p class="text-lg">{{ post.price }}</p> 
                                </div>
                                <div>
                                        <p class="text-sm">수량</p>
                                        <p class="text-lg">{{ post.amount }}</p> 
                                </div>
                        </div>      
                </div>
                
                <p class="font-semibold">매매이유</p>
                <p class="text-sm">{{post.description}}</p>
                <div class="py-2 flex justify-center gap-2">
                        <a class="px-2 border-2 border-primary rounded-2xl" href="{% url 'tradelog:update' post.id %}">수정</a>
                        <a class="px-2 border-2 border-primary rounded-2xl" href="{% url 'tradelog:delete' post.id %}">삭제</a>
                </div>
                <p class="text-xs text-right">{{ post.trade_at|date:"Y-m-d" }}</p>
                <!-- <a href="{% url 'tradelog:detail' post.id %}"><h3>날짜 : {{ post.create_at }}</h3></a>
                <h4>종목명 : {{ post.name }}</h4>
                <h4>가격 : {{ post.price }}</h4>
                <h4>체결량 : {{ post.amount }}</h4>

                <a href="{% url 'tradelog:update' post.id %}">수정하기</a>
                <a href="{% url 'tradelog:delete' post.id %}">글 삭제하기</a> -->
        </div>

{% endfor %}

templates/tradelog/form_create.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.full.js"></script>

{% if isCreate %}
<div class="w-screen h-screen bg-black bg-opacity-30 fixed flex justify-center items-center" 
    id="feed-create-layer-popup" onclick="goToDashboard(event)">
    <div class="w-1/2 h-auto m-auto bg-white">
        <h1 class="text-custom_black">매매일지 작성하기</h1>
        <div class="flex-col text-red-400 p-4">
            <p>{{ failed_message }}</p>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}  
            <table>
                {{ form.as_table }}
                {{ form.media }}
            </table>
            <input type="submit" value="새 글 생성하기">
        </form>
    </div>
</div>

<script>
    function goToDashboard(event){
        console.log(event);
        const layerPopup = document.querySelector("#feed-create-layer-popup");
        if(event.target=== layerPopup)
        {
            window.history.back();
        }
    }
</script>


{% endif %}

templates/tradelog/sidebar_right.html
{% load static %}
<div class="p-4 h-14 bg-primary">
    <p class="text-white font-semibold">RANKING</p>
</div>
{% for name, amount in mystock_rank.items %}
<div class="p-4 border-b flex justify-between">
    <div>
        <span class="font-semibold text-lg px-4">1</span>
        <img src="{% static '/image/profileimg_empty.png' %}" class="w-8 h-8 rounded-full bg-gray-100 inline"/>
        <span>{{name}}</span>
    </div>
    <div class="px-8">
        {{amount}}
    </div>
</div>
{% endfor %}

templates/tradelog/update.html
<!-- <h1>매매일지 수정하기</h1>

<div class="flex-col text-red-400 p-4">
    <p>{{ failed_message }}</p>
</div>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}  
    <table>
        {{ update_form.as_table }}
    </table>
    <input type="submit" value="수정하기">
</form> -->

{% if isUpdate %}
<div class="w-screen h-screen bg-black bg-opacity-30 fixed flex justify-center items-center" 
    id="feed-create-layer-popup" onclick="goToDashboard(event)">
    <div class="w-1/2 h-auto m-auto bg-white">
        <h1 class="text-custom_black">매매일지 수정하기</h1>
        <div class="flex-col text-red-400 p-4">
            <p>{{ failed_message }}</p>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}  
            <table>
                {{ update_form.as_table }}
            </table>
            <input type="submit" value="수정하기">
        </form>
    </div>
</div>

<script>
    function goToDashboard(event){
        console.log(event);
        const layerPopup = document.querySelector("#feed-create-layer-popup");
        if(event.target=== layerPopup)
        {
            window.history.back();
        }
    }
</script>

{% endif %}